// <auto-generated />
using System;
using CreditFlow.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditFlow.Infrastructure.Migrations
{
    [DbContext(typeof(CreditFlowDbContext))]
    [Migration("20260723143320_AddUsageEvents")]
    partial class AddUsageEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("CreditFlow.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "billing@acmelabs.example",
                            Name = "Acme Labs"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "ops@northwind.example",
                            Name = "Northwind Analytics"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "finance@bluebird.example",
                            Name = "Bluebird Systems"
                        });
                });

            modelBuilder.Entity("CreditFlow.Domain.CreditLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("CreditLedgerEntries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            AccountId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Amount = 300,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Initial monthly grant",
                            IdempotencyKey = "seed-acme-grant-1",
                            ReferenceId = "seed-acme-sub-1",
                            Source = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            AccountId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Amount = -80,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 5, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Model inference usage",
                            IdempotencyKey = "seed-acme-use-1",
                            ReferenceId = "seed-acme-event-1",
                            Source = 3,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-000000000001"),
                            AccountId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Amount = 100,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Starter credit pack",
                            IdempotencyKey = "seed-nw-pack-1",
                            ReferenceId = "seed-nw-packref-1",
                            Source = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-000000000002"),
                            AccountId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Amount = -20,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 9, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "API usage",
                            IdempotencyKey = "seed-nw-use-1",
                            ReferenceId = "seed-nw-event-1",
                            Source = 3,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000001"),
                            AccountId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Amount = 500,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Enterprise monthly allowance",
                            IdempotencyKey = "seed-bluebird-grant-1",
                            ReferenceId = "seed-bluebird-sub-1",
                            Source = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000002"),
                            AccountId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Amount = 40,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Promotional adjustment",
                            IdempotencyKey = "seed-bluebird-adj-1",
                            ReferenceId = "seed-bluebird-adjref-1",
                            Source = 4,
                            Type = 5
                        });
                });

            modelBuilder.Entity("CreditFlow.Domain.UsageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("UsageEvents", (string)null);
                });

            modelBuilder.Entity("CreditFlow.Domain.CreditLedgerEntry", b =>
                {
                    b.HasOne("CreditFlow.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CreditFlow.Domain.UsageEvent", b =>
                {
                    b.HasOne("CreditFlow.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
